# Site settings
title: XZ Blog
SEOTitle: 小站的博客 | XZ Blog
header-img: img/post-bg-rwd.jpg
email: 2457307263@qq.com
description: "Stay Hungry , Stay foolish."
keyword: "XZ, XZ Blog, 小站的博客, 王小站, wangxiaozhan, 前端, javascript, Node"
url: "http://wangxiaozhan.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "工地工人与砖!"
sidebar-avatar: /img/avatar_m.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     xiao-zhan-57-36
github_username:    wangxiaozhan
facebook_username:  
jianshu_username:   e010cceb794c
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 613641b826932032869f                            #生成的clientID
  clientSecret: 9f746c6da6fe7afc3ae3cb98bd98025f0103d15b    #生成的clientSecret
  repo: wangxiaozhan.github.io    #仓库名称
  owner: wangxiaozhan    #github用户名
  admin: wangxiaozhan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname'


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: d41292da7924274aa25e75f9069c226e

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "node.js学习社区",
        href: "http://www.nodeclass.com"
    },
]
